### ISSUE TITLE
PiCamera2 on Python 3.10?

### ISSUE THREAD

**Issue by magsol** [magsol/wildlife-cameras#1]
So far, this seems infeasible.

`sudo apt-get install python3-libcamera` seems to be the only way to perform a package install of libcamera, which is needed for PiCamera2. However, this ties itself to the _system_ Python, which is 3.9. I tried symlinking the libcamera folder into the conda environment with Python 3.10, but was stymied by this error:

```
$ python -c "import libcamera"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/envs/py310/lib/python3.10/site-packages/libcamera/__init__.py", line 4, in <module>
    from ._libcamera import *
ModuleNotFoundError: No module named 'libcamera._libcamera'
```

There doesn't seem to be a way around this, short of [building from source](https://libcamera.org/getting-started.html).

Conversely, doing the same symlink in the default mamba environment (which also uses Python 3.9), importing libcamera worked just fine. So I guess we'll just have to stick with Python 3.9.

**Comment by magsol** [comment]
Closed as can't use on Python 3.10 for the time being.
