### ISSUE TITLE
RuntimeError: MappedArray: Cannot reshape buffer 3280x2464x3

### ISSUE THREAD

**Issue by magsol** [magsol/wildlife-cameras#12]
Running into some kind of shape error when I try to apply a timestamp to the photo:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python/envs/picam/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/python/envs/picam/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python/envs/picam/lib/python3.9/site-packages/picamera2/previews/null_preview.py", line 25, in thread_func
    callback(picam2)
  File "/opt/python/envs/picam/lib/python3.9/site-packages/picamera2/previews/null_preview.py", line 72, in handle_request
    completed_request = picam2.process_requests()
  File "/opt/python/envs/picam/lib/python3.9/site-packages/picamera2/picamera2.py", line 877, in process_requests
    self.pre_callback(display_request)
  File "/home/squinn/picam.py", line 11, in apply_timestamp
    with MappedArray(request, "main") as m:
  File "/opt/python/envs/picam/lib/python3.9/site-packages/picamera2/request.py", line 62, in __enter__
    raise RuntimeError(f'MappedArray: Cannot reshape buffer {w}x{h}x3 (stride {stride})')
RuntimeError: MappedArray: Cannot reshape buffer 3280x2464x3 (stride 9888)
```

Opened an issue with the Picamera2 folks: https://github.com/raspberrypi/picamera2/issues/239

**Comment by magsol** [comment]
Should help address #5 as well since the examples already work for video, just not stills.
